import { inject, singleton } from 'tsyringe';
import { z } from 'zod';
import type { Request, Response } from 'express';
import type { RouteConfig } from '@asteasolutions/zod-to-openapi';
import wrtc from '@roamhq/wrtc';
import { SessionManager } from '../channels/SessionManager';
import type { Session } from '../channels/SessionManager';
import { ChannelHandlerDispatcher } from '../channels/ChannelHandlerDispatcher';
import { IpRateLimiter } from '../IpRateLimiter';
import { WebRTCConnection } from './WebRTCConnection';
import { asyncHandler } from '../utils/asyncHandler';
import type { BaseInputMessage } from '../websocket/contracts/common';
import type { CALInputMessage } from '../channels/messages';
import type { ClientMessageHandlerContext } from '../channels/ClientMessageHandlerContext';
import { logger } from '../utils/logger';

const { RTCPeerConnection: NodeRTCPeerConnection } = wrtc as unknown as { RTCPeerConnection: typeof RTCPeerConnection };

const ICE_GATHERING_TIMEOUT_MS = parseInt(process.env.WEBRTC_ICE_GATHERING_TIMEOUT_MS ?? '5000', 10);
const STUN_URL = process.env.WEBRTC_STUN_URL ?? 'stun:stun.l.google.com:19302';

/**
 * Decodes a binary audio frame received on the audio DataChannel.
 *
 * Frame format: [2 bytes: turnId length as uint16 LE] [N bytes: turnId as UTF-8] [remaining: raw audio]
 */
function decodeAudioFrame(data: Buffer): { turnId: string; audioData: Buffer } | null {
  if (data.length < 2) return null;
  const turnIdLength = data.readUInt16LE(0);
  if (data.length < 2 + turnIdLength) return null;
  const turnId = data.subarray(2, 2 + turnIdLength).toString('utf8');
  const audioData = Buffer.from(data.subarray(2 + turnIdLength));
  return { turnId, audioData };
}

/**
 * Waits for RTCPeerConnection ICE gathering to complete, or resolves after a timeout.
 * With a public-IP server and STUN only, gathering typically completes in milliseconds.
 */
function waitForIceGathering(pc: RTCPeerConnection): Promise<void> {
  if (pc.iceGatheringState === 'complete') return Promise.resolve();

  return new Promise<void>((resolve) => {
    const timeout = setTimeout(() => {
      logger.warn('WebRTC ICE gathering timed out, proceeding with available candidates');
      resolve();
    }, ICE_GATHERING_TIMEOUT_MS);

    pc.onicegatheringstatechange = () => {
      if (pc.iceGatheringState === 'complete') {
        clearTimeout(timeout);
        resolve();
      }
    };
  });
}

const webRTCOfferBodySchema = z.object({
  sdpOffer: z.string().describe('SDP offer string generated by the client RTCPeerConnection'),
});

const webRTCOfferResponseSchema = z.object({
  sdpAnswer: z.string().describe('SDP answer with all ICE candidates embedded (gather-and-return, no trickle ICE)'),
});

/**
 * WebRTC channel host that manages peer connections, signaling, and message routing.
 *
 * Provides a single HTTP POST endpoint for SDP offer/answer exchange. After the peer
 * connection is established, the client communicates over two named DataChannels:
 * - `control` (ordered, reliable): JSON messages using the same protocol as WebSocket
 * - `audio` (unordered, maxRetransmits: 0): binary audio frames for user voice input
 *
 * Binary audio frame format (inbound user voice):
 * [2 bytes: inputTurnId length as uint16 LE] [N bytes: inputTurnId as UTF-8] [remaining: raw audio]
 *
 * AI voice output is sent to the client over the `audio` DataChannel using the same frame format
 * with outputTurnId as the turn identifier.
 *
 * Environment variables:
 * - `WEBRTC_ICE_GATHERING_TIMEOUT_MS` — max ms to wait for ICE gather (default: 5000)
 * - `WEBRTC_STUN_URL` — STUN server URL (default: stun:stun.l.google.com:19302)
 */
@singleton()
export class WebRTCChannelHost {
  private peerConnections: Map<string, RTCPeerConnection> = new Map();

  constructor(
    @inject(ChannelHandlerDispatcher) private readonly dispatcher: ChannelHandlerDispatcher,
    @inject(SessionManager) private readonly sessionManager: SessionManager,
    @inject(IpRateLimiter) private readonly rateLimiter: IpRateLimiter,
  ) {}

  /**
   * Returns OpenAPI route configurations for the WebRTC signaling endpoint.
   */
  static getOpenAPIPaths(): RouteConfig[] {
    return [
      {
        method: 'post',
        path: '/api/webrtc/offer',
        tags: ['WebRTC'],
        summary: 'Exchange SDP offer/answer for WebRTC session',
        description:
          'Accepts a WebRTC SDP offer from the client and returns an SDP answer with all ICE candidates embedded ' +
          '(gather-and-return; no trickle ICE). ' +
          'Before creating the offer the client must open two named DataChannels: ' +
          '"control" (ordered: true) for all JSON messages (same protocol as WebSocket) and ' +
          '"audio" (ordered: false, maxRetransmits: 0) for binary audio frames. ' +
          'Audio frame format: [uint16 LE: turnId byte length] [turnId UTF-8 bytes] [raw PCM audio]. ' +
          'Once the DataChannels are open, authenticate by sending an "auth" JSON message over the control channel.',
        security: [],
        request: {
          body: {
            content: {
              'application/json': { schema: webRTCOfferBodySchema },
            },
          },
        },
        responses: {
          200: {
            description: 'SDP answer returned successfully',
            content: {
              'application/json': { schema: webRTCOfferResponseSchema },
            },
          },
          400: { description: 'Missing or invalid sdpOffer' },
          500: { description: 'Failed to create peer connection or generate ICE answer' },
        },
      },
    ];
  }

  /**
   * Registers the WebRTC signaling route on the given Express application.
   * @param app - The Express application or router.
   */
  registerRoutes(app: any): void {
    app.post('/api/webrtc/offer', asyncHandler(this.handleOffer.bind(this)));
  }

  /**
   * Handles a WebRTC SDP offer: creates a peer connection, generates an answer,
   * waits for ICE gathering to complete, and returns the answer.
   * Session and DataChannel setup happen asynchronously after the ICE connection is established.
   */
  private async handleOffer(req: Request, res: Response): Promise<void> {
    const parsed = webRTCOfferBodySchema.safeParse(req.body);
    if (!parsed.success) {
      res.status(400).json({ error: 'sdpOffer is required and must be a string' });
      return;
    }

    const clientIp = String(req.ip ?? req.socket?.remoteAddress ?? '').replace(/^::ffff:/, '');
    const { sdpOffer } = parsed.data;

    logger.info({ ip: clientIp }, 'WebRTC offer received');

    let pc: RTCPeerConnection;
    try {
      pc = new NodeRTCPeerConnection({ iceServers: [{ urls: STUN_URL }] });
    } catch (err) {
      logger.error({ error: err }, 'Failed to create RTCPeerConnection');
      res.status(500).json({ error: 'Failed to initialise WebRTC peer connection' });
      return;
    }

    let controlChannel: RTCDataChannel | null = null;
    let audioChannel: RTCDataChannel | null = null;

    pc.ondatachannel = (event: RTCDataChannelEvent) => {
      const channel = event.channel;
      if (channel.label === 'control') {
        controlChannel = channel;
      } else if (channel.label === 'audio') {
        audioChannel = channel;
      }

      if (controlChannel && audioChannel) {
        const ctrl = controlChannel;
        const aud = audioChannel;
        const waitOpen = (ch: RTCDataChannel): Promise<void> =>
          ch.readyState === 'open' ? Promise.resolve() : new Promise<void>((resolve) => { ch.onopen = () => resolve(); });

        Promise.all([waitOpen(ctrl), waitOpen(aud)])
          .then(() => this.setupConnection(pc, ctrl, aud, clientIp))
          .catch((err) => logger.error({ error: err, ip: clientIp }, 'WebRTC DataChannels failed to open'));
      }
    };

    pc.onconnectionstatechange = () => {
      if (pc.connectionState === 'failed' || pc.connectionState === 'closed') {
        logger.info({ connectionState: pc.connectionState, ip: clientIp }, 'WebRTC peer connection closed or failed');
        this.cleanupPeerConnection(pc);
      }
    };

    try {
      await pc.setRemoteDescription({ type: 'offer', sdp: sdpOffer });
      const answer = await pc.createAnswer();
      await pc.setLocalDescription(answer);
      await waitForIceGathering(pc);
    } catch (err) {
      logger.error({ error: err, ip: clientIp }, 'WebRTC signaling failed');
      pc.close();
      res.status(500).json({ error: 'WebRTC signaling failed' });
      return;
    }

    res.status(200).json({ sdpAnswer: pc.localDescription!.sdp });
  }

  /**
   * Creates a {@link WebRTCConnection} and registers a session once both DataChannels are open.
   * Wires up message handlers for the control and audio channels.
   */
  private setupConnection(pc: RTCPeerConnection, controlChannel: RTCDataChannel, audioChannel: RTCDataChannel, clientIp: string): void {
    const webrtcConnection = new WebRTCConnection(controlChannel, audioChannel, this.sessionManager);
    const sessionId = this.sessionManager.registerSession(webrtcConnection);
    const session = this.sessionManager.getSession(sessionId);
    webrtcConnection.attachSession(session);

    this.peerConnections.set(sessionId, pc);

    logger.info({ sessionId, ip: clientIp }, 'WebRTC DataChannels open, session created');

    controlChannel.onmessage = (event: MessageEvent) => {
      this.handleControlMessage(webrtcConnection, session, event.data as string, clientIp);
    };

    audioChannel.onmessage = (event: MessageEvent) => {
      const raw = event.data;
      const buffer: Buffer = Buffer.isBuffer(raw) ? raw : Buffer.from(raw as ArrayBuffer);
      this.handleAudioMessage(session, buffer);
    };

    controlChannel.onclose = () => {
      this.handleDisconnect(session.id);
    };
  }

  /**
   * Handles a JSON control message from the client.
   * Translates the wire format to CAL format and dispatches to the appropriate handler.
   */
  private async handleControlMessage(connection: WebRTCConnection, session: Session, data: string, clientIp: string): Promise<void> {
    let wsMessage: BaseInputMessage;
    try {
      wsMessage = JSON.parse(data) as BaseInputMessage;
    } catch {
      connection.sendError('Invalid JSON');
      return;
    }

    if (wsMessage.type === 'auth') {
      if (!this.rateLimiter.tryConsume(clientIp)) {
        const retryAfter = this.rateLimiter.getRetryAfterSeconds(clientIp);
        logger.warn({ ip: clientIp, retryAfter }, 'WebRTC auth rate limit exceeded');
        connection.sendError('Too many authentication attempts, please try again later', wsMessage.requestId);
        await connection.close();
        return;
      }
    }

    const calMessage = {
      ...wsMessage,
      correlationId: wsMessage.requestId,
      conversationId: session?.conversationId ?? '',
    } as CALInputMessage;

    const context: ClientMessageHandlerContext = {
      session,
      send: (msg: any) => {
        const outMsg: Record<string, unknown> = { ...msg };
        if (!outMsg.requestId && outMsg.correlationId) outMsg.requestId = outMsg.correlationId;
        if (!outMsg.sessionId && session?.id) outMsg.sessionId = session.id;
        connection.sendRawControl(outMsg);
      },
      sendError: (error: string, correlationId?: string) => connection.sendError(error, correlationId),
    };

    await this.dispatcher.dispatch(calMessage, context);
  }

  /**
   * Handles a binary audio frame from the user's audio DataChannel.
   * Decodes the frame and forwards the raw PCM buffer directly to the conversation runner,
   * bypassing the handler dispatcher to avoid base64 encode/decode overhead.
   */
  private async handleAudioMessage(session: Session, data: Buffer): Promise<void> {
    if (!session?.conversationId || !session?.runner) {
      logger.debug({ sessionId: session?.id }, 'WebRTC audio frame received before conversation started, ignoring');
      return;
    }

    const decoded = decodeAudioFrame(data);
    if (!decoded) {
      logger.warn({ sessionId: session?.id }, 'WebRTC received malformed audio frame, ignoring');
      return;
    }

    try {
      await session.runner.receiveUserVoiceData(decoded.turnId, decoded.audioData);
    } catch (err) {
      logger.error({ error: err, sessionId: session?.id }, 'WebRTC failed to process audio frame');
    }
  }

  /**
   * Handles DataChannel disconnection: closes the peer connection and unregisters the session.
   */
  private async handleDisconnect(sessionId: string): Promise<void> {
    logger.info({ sessionId }, 'WebRTC control channel closed, cleaning up session');
    const pc = this.peerConnections.get(sessionId);
    if (pc) {
      pc.close();
      this.peerConnections.delete(sessionId);
    }
    await this.sessionManager.unregisterSession(sessionId);
  }

  /**
   * Removes a peer connection from the internal map by reference.
   */
  private cleanupPeerConnection(pc: RTCPeerConnection): void {
    for (const [sessionId, storedPc] of this.peerConnections) {
      if (storedPc === pc) {
        this.peerConnections.delete(sessionId);
        break;
      }
    }
  }
}
