import { inject, singleton } from 'tsyringe';
import { z } from 'zod';
import type { Request, Response } from 'express';
import type { RouteConfig } from '@asteasolutions/zod-to-openapi';
import wrtc from '@roamhq/wrtc';
import { SessionManager } from '../SessionManager';
import type { Session } from '../SessionManager';
import { ChannelHandlerDispatcher } from '../ChannelHandlerDispatcher';
import { IpRateLimiter } from '../../IpRateLimiter';
import { WebRTCConnection } from './WebRTCConnection';
import { asyncHandler } from '../../utils/asyncHandler';
import type { BaseInputMessage } from '../websocket/contracts/common';
import type { CALInputMessage } from '../messages';
import type { ClientMessageHandlerContext } from '../ClientMessageHandlerContext';
import { logger } from '../../utils/logger';

/** Shape of PCM audio data received from an RTCAudioSink data event. */
type RTCAudioSinkData = {
  samples: Int16Array;
  sampleRate: number;
  bitsPerSample: number;
  channelCount: number;
  numberOfFrames: number;
};

/** Minimal interface for the node-webrtc RTCAudioSource nonstandard API. */
type RTCAudioSourceType = {
  createTrack(): MediaStreamTrack;
  onData(data: { samples: Int16Array; sampleRate: number; bitsPerSample?: number; channelCount?: number; numberOfFrames?: number }): void;
};

/** Minimal interface for the node-webrtc RTCAudioSink nonstandard API. */
type RTCAudioSinkType = {
  stop(): void;
  readonly stopped: boolean;
  ondata: ((data: RTCAudioSinkData) => void) | null;
};

/** Constructor types extracted from the wrtc.nonstandard namespace. */
type WrtcNonstandard = {
  RTCAudioSource: { new(): RTCAudioSourceType };
  RTCAudioSink: { new(track: MediaStreamTrack): RTCAudioSinkType };
};

const { RTCPeerConnection: NodeRTCPeerConnection, nonstandard } = wrtc as unknown as {
  RTCPeerConnection: typeof RTCPeerConnection;
  nonstandard: WrtcNonstandard;
};
const { RTCAudioSource: NodeRTCAudioSource, RTCAudioSink: NodeRTCAudioSink } = nonstandard;

const ICE_GATHERING_TIMEOUT_MS = parseInt(process.env.WEBRTC_ICE_GATHERING_TIMEOUT_MS ?? '5000', 10);
const STUN_URL = process.env.WEBRTC_STUN_URL ?? 'stun:stun.l.google.com:19302';

/**
 * Waits for RTCPeerConnection ICE gathering to complete, or resolves after a timeout.
 * With a public-IP server and STUN only, gathering typically completes in milliseconds.
 */
function waitForIceGathering(pc: RTCPeerConnection): Promise<void> {
  if (pc.iceGatheringState === 'complete') return Promise.resolve();

  return new Promise<void>((resolve) => {
    const timeout = setTimeout(() => {
      logger.warn('WebRTC ICE gathering timed out, proceeding with available candidates');
      resolve();
    }, ICE_GATHERING_TIMEOUT_MS);

    pc.onicegatheringstatechange = () => {
      if (pc.iceGatheringState === 'complete') {
        clearTimeout(timeout);
        resolve();
      }
    };
  });
}

const webRTCOfferBodySchema = z.object({
  sdpOffer: z.string().describe('SDP offer string generated by the client RTCPeerConnection'),
});

const webRTCOfferResponseSchema = z.object({
  sdpAnswer: z.string().describe('SDP answer with all ICE candidates embedded (gather-and-return, no trickle ICE)'),
});

/**
 * WebRTC channel host that manages peer connections, signaling, and message routing.
 *
 * Provides a single HTTP POST endpoint for SDP offer/answer exchange. After the peer
 * connection is established, the client communicates over:
 * - `control` DataChannel (ordered, reliable): JSON messages using the same protocol as WebSocket
 * - Native audio media track (RTP/SRTP + Opus): bidirectional voice audio
 *
 * The server creates an RTCAudioSource for outbound AI voice and an RTCAudioSink for inbound
 * user voice. The client should add its microphone track to the offer so server-side VAD and
 * ASR can process voice input.
 *
 * Environment variables:
 * - `WEBRTC_ICE_GATHERING_TIMEOUT_MS` — max ms to wait for ICE gather (default: 5000)
 * - `WEBRTC_STUN_URL` — STUN server URL (default: stun:stun.l.google.com:19302)
 */
@singleton()
export class WebRTCChannelHost {
  private peerConnections: Map<string, { pc: RTCPeerConnection; audioSink: RTCAudioSinkType | null }> = new Map();

  constructor(
    @inject(ChannelHandlerDispatcher) private readonly dispatcher: ChannelHandlerDispatcher,
    @inject(SessionManager) private readonly sessionManager: SessionManager,
    @inject(IpRateLimiter) private readonly rateLimiter: IpRateLimiter,
  ) {}

  /**
   * Returns OpenAPI route configurations for the WebRTC signaling endpoint.
   */
  static getOpenAPIPaths(): RouteConfig[] {
    return [
      {
        method: 'post',
        path: '/api/webrtc/offer',
        tags: ['WebRTC'],
        summary: 'Exchange SDP offer/answer for WebRTC session',
        description:
          'Accepts a WebRTC SDP offer from the client and returns an SDP answer with all ICE candidates embedded ' +
          '(gather-and-return; no trickle ICE). ' +
          'The client must add a microphone audio track and open a "control" DataChannel (ordered: true) before creating the offer. ' +
          'The server adds an outbound audio track to the answer for AI voice output. ' +
          'Once the control DataChannel is open, authenticate by sending an "auth" JSON message over it. ' +
          'All JSON messages use the same protocol as WebSocket. Voice audio flows over native RTP/SRTP media tracks.',
        security: [],
        request: {
          body: {
            content: {
              'application/json': { schema: webRTCOfferBodySchema },
            },
          },
        },
        responses: {
          200: {
            description: 'SDP answer returned successfully',
            content: {
              'application/json': { schema: webRTCOfferResponseSchema },
            },
          },
          400: { description: 'Missing or invalid sdpOffer' },
          500: { description: 'Failed to create peer connection or generate ICE answer' },
        },
      },
    ];
  }

  /**
   * Registers the WebRTC signaling route on the given Express application.
   * @param app - The Express application or router.
   */
  registerRoutes(app: any): void {
    app.post('/api/webrtc/offer', asyncHandler(this.handleOffer.bind(this)));
  }

  /**
   * Handles a WebRTC SDP offer: creates a peer connection, registers an outbound audio track,
   * generates an answer, waits for ICE gathering to complete, and returns the answer.
   * Session setup happens asynchronously after the control DataChannel is established.
   */
  private async handleOffer(req: Request, res: Response): Promise<void> {
    const parsed = webRTCOfferBodySchema.safeParse(req.body);
    if (!parsed.success) {
      res.status(400).json({ error: 'sdpOffer is required and must be a string' });
      return;
    }

    const clientIp = String(req.ip ?? req.socket?.remoteAddress ?? '').replace(/^::ffff:/, '');
    const { sdpOffer } = parsed.data;

    logger.info({ ip: clientIp }, 'WebRTC offer received');

    let pc: RTCPeerConnection;
    try {
      pc = new NodeRTCPeerConnection({ iceServers: [{ urls: STUN_URL }] });
    } catch (err) {
      logger.error({ error: err }, 'Failed to create RTCPeerConnection');
      res.status(500).json({ error: 'Failed to initialise WebRTC peer connection' });
      return;
    }

    // Create the outbound audio source for AI voice output and add the track to the PC
    // before setRemoteDescription so it is included in the SDP answer.
    const audioSource = new NodeRTCAudioSource();
    const outboundTrack = audioSource.createTrack();
    pc.addTrack(outboundTrack);

    // Capture the client's inbound audio track when the offer is processed.
    let inboundAudioTrack: MediaStreamTrack | null = null;
    pc.ontrack = (event: RTCTrackEvent) => {
      if (event.track.kind === 'audio') {
        inboundAudioTrack = event.track;
        logger.debug({ ip: clientIp }, 'WebRTC inbound audio track received');
      }
    };

    let controlChannel: RTCDataChannel | null = null;

    pc.ondatachannel = (event: RTCDataChannelEvent) => {
      const channel = event.channel;
      if (channel.label === 'control') {
        controlChannel = channel;
        const waitOpen = (ch: RTCDataChannel): Promise<void> =>
          ch.readyState === 'open' ? Promise.resolve() : new Promise<void>((resolve) => { ch.onopen = () => resolve(); });

        waitOpen(channel)
          .then(() => this.setupConnection(pc, controlChannel!, audioSource, inboundAudioTrack, clientIp))
          .catch((err) => logger.error({ error: err, ip: clientIp }, 'WebRTC control channel failed to open'));
      }
    };

    pc.onconnectionstatechange = () => {
      if (pc.connectionState === 'failed' || pc.connectionState === 'closed') {
        logger.info({ connectionState: pc.connectionState, ip: clientIp }, 'WebRTC peer connection closed or failed');
        this.cleanupPeerConnection(pc);
      }
    };

    try {
      await pc.setRemoteDescription({ type: 'offer', sdp: sdpOffer });
      const answer = await pc.createAnswer();
      await pc.setLocalDescription(answer);
      await waitForIceGathering(pc);
    } catch (err) {
      logger.error({ error: err, ip: clientIp }, 'WebRTC signaling failed');
      pc.close();
      res.status(500).json({ error: 'WebRTC signaling failed' });
      return;
    }

    res.status(200).json({ sdpAnswer: pc.localDescription!.sdp });
  }

  /**
   * Creates a {@link WebRTCConnection}, registers a session, and wires up message handlers
   * for the control DataChannel and the native audio media track.
   * If an inbound audio track was received, an RTCAudioSink is created to forward PCM frames
   * to the conversation runner.
   */
  private setupConnection(pc: RTCPeerConnection, controlChannel: RTCDataChannel, audioSource: RTCAudioSourceType, inboundAudioTrack: MediaStreamTrack | null, clientIp: string): void {
    const webrtcConnection = new WebRTCConnection(controlChannel, audioSource, this.sessionManager);
    const sessionId = this.sessionManager.registerSession(webrtcConnection);
    const session = this.sessionManager.getSession(sessionId);
    webrtcConnection.attachSession(session);

    const audioSink: RTCAudioSinkType | null = inboundAudioTrack ? new NodeRTCAudioSink(inboundAudioTrack) : null;
    this.peerConnections.set(sessionId, { pc, audioSink });

    logger.info({ sessionId, ip: clientIp, hasAudioTrack: !!inboundAudioTrack }, 'WebRTC control channel open, session created');

    if (audioSink) {
      audioSink.ondata = (data: RTCAudioSinkData) => {
        if (!session?.conversationId || !session?.runner) return;
        const pcmBuffer = Buffer.from(data.samples.buffer.slice(data.samples.byteOffset, data.samples.byteOffset + data.samples.byteLength));
        session.runner.receiveUserVoiceData(webrtcConnection.getActiveInputTurnId() ?? '', pcmBuffer).catch((err) => {
          logger.error({ error: err, sessionId: session?.id }, 'WebRTC failed to process inbound audio frame');
        });
      };
    }

    controlChannel.onmessage = (event: MessageEvent) => {
      this.handleControlMessage(webrtcConnection, session, event.data as string, clientIp);
    };

    controlChannel.onclose = () => {
      this.handleDisconnect(session.id);
    };
  }

  /**
   * Handles a JSON control message from the client.
   * Translates the wire format to CAL format and dispatches to the appropriate handler.
   */
  private async handleControlMessage(connection: WebRTCConnection, session: Session, data: string, clientIp: string): Promise<void> {
    let wsMessage: BaseInputMessage;
    try {
      wsMessage = JSON.parse(data) as BaseInputMessage;
    } catch {
      connection.sendError('Invalid JSON');
      return;
    }

    if (wsMessage.type === 'auth') {
      if (!this.rateLimiter.tryConsume(clientIp)) {
        const retryAfter = this.rateLimiter.getRetryAfterSeconds(clientIp);
        logger.warn({ ip: clientIp, retryAfter }, 'WebRTC auth rate limit exceeded');
        connection.sendError('Too many authentication attempts, please try again later', wsMessage.requestId);
        await connection.close();
        return;
      }
    }

    const calMessage = {
      ...wsMessage,
      correlationId: wsMessage.requestId,
      conversationId: session?.conversationId ?? '',
    } as CALInputMessage;

    const context: ClientMessageHandlerContext = {
      session,
      send: (msg: any) => {
        const outMsg: Record<string, unknown> = { ...msg };
        if (!outMsg.requestId && outMsg.correlationId) outMsg.requestId = outMsg.correlationId;
        if (!outMsg.sessionId && session?.id) outMsg.sessionId = session.id;
        // Keep the active input turn ID in sync with voice input lifecycle messages so
        // the audio sink knows which turn to forward inbound audio to.
        if (outMsg.type === 'start_user_voice_input' && outMsg.success && outMsg.inputTurnId) {
          connection.setActiveInputTurnId(outMsg.inputTurnId as string);
        } else if (outMsg.type === 'end_user_voice_input' && outMsg.success) {
          connection.clearActiveInputTurnId();
        }
        connection.sendRawControl(outMsg);
      },
      sendError: (error: string, correlationId?: string) => connection.sendError(error, correlationId),
    };

    await this.dispatcher.dispatch(calMessage, context);
  }

  /**
   * Handles DataChannel disconnection: stops the audio sink, closes the peer connection,
   * and unregisters the session.
   */
  private async handleDisconnect(sessionId: string): Promise<void> {
    logger.info({ sessionId }, 'WebRTC control channel closed, cleaning up session');
    const entry = this.peerConnections.get(sessionId);
    if (entry) {
      entry.audioSink?.stop();
      entry.pc.close();
      this.peerConnections.delete(sessionId);
    }
    await this.sessionManager.unregisterSession(sessionId);
  }

  /**
   * Removes a peer connection from the internal map by reference.
   */
  private cleanupPeerConnection(pc: RTCPeerConnection): void {
    for (const [sessionId, entry] of this.peerConnections) {
      if (entry.pc === pc) {
        entry.audioSink?.stop();
        this.peerConnections.delete(sessionId);
        break;
      }
    }
  }
}
