import { z } from 'zod';
import { extendZodWithOpenApi } from '@asteasolutions/zod-to-openapi';
import { relativeTimeSchema } from './sliceAnalytics';

extendZodWithOpenApi(z);

/**
 * Supported event types for funnel step matching.
 * Each type maps to one or more conversation event records in the database.
 */
export const funnelEventTypeSchema = z.enum([
  'enter_stage',
  'end_stage',
  'action_fire',
  'variable_changed',
  'user_profile_changed',
  'session_started',
  'tool_response',
]).describe('Event type that defines this funnel step');

export type FunnelEventType = z.infer<typeof funnelEventTypeSchema>;

/**
 * A single step in a funnel definition.
 * The required keys in `params` depend on the chosen `eventType`.
 *
 * Params per eventType:
 * - enter_stage:          required: stageName
 * - end_stage:            required: stageName; optional: reason
 * - action_fire:          required: actionName
 * - variable_changed:     required: variableName; optional: value
 * - user_profile_changed: required: profileName;  optional: value
 * - session_started:      required: minSessions (string-encoded positive integer)
 * - tool_response:        required: toolName, value (exact match on result[0].text)
 */
export const funnelStepSchema = z.object({
  eventType: funnelEventTypeSchema,
  params: z.record(z.string(), z.string()).describe('Event-specific filter parameters; see FunnelStep documentation for required keys per eventType'),
}).openapi('FunnelStep');

export type FunnelStep = z.infer<typeof funnelStepSchema>;

/**
 * A funnel query definition — the stored payload for a saved funnel query.
 * Requires between 2 and 15 steps and exactly one time-range specification.
 */
export const funnelQuerySchema = z.object({
  steps: z.array(funnelStepSchema).max(15).describe('Ordered list of funnel steps; minimum 2, maximum 15'),
  relativeTime: relativeTimeSchema.optional().describe('Relative look-back window (mutually exclusive with from/to)'),
  from: z.coerce.date().optional().describe('Time window start, inclusive (ISO 8601; mutually exclusive with relativeTime)'),
  to: z.coerce.date().optional().describe('Time window end, inclusive (ISO 8601; mutually exclusive with relativeTime)'),
}).openapi('FunnelQuery');

export type FunnelQueryRequest = z.infer<typeof funnelQuerySchema>;

/**
 * Result data for a single step in the funnel response.
 */
export const funnelStepResultSchema = z.object({
  stepNumber: z.number().int().describe('1-based index of this step in the input steps array'),
  label: z.string().describe('Human-readable label generated by the server'),
  userCount: z.number().int().describe('Absolute count of unique users who reached this step'),
  percentage: z.number().describe('userCount / usersAtStart × 100; always 100.0 for step 1'),
  dropoffCount: z.number().int().describe('Users lost relative to the previous step; 0 for step 1'),
  dropoffPercentage: z.number().describe('dropoffCount / usersAtStart × 100; 0.0 for step 1'),
}).openapi('FunnelStepResult');

export type FunnelStepResult = z.infer<typeof funnelStepResultSchema>;

/**
 * Response body for a successful funnel query execution.
 */
export const funnelQueryResponseSchema = z.object({
  totalConversionRate: z.number().describe('Percentage of step-1 users who reached the last step (0.0–100.0)'),
  usersAtStart: z.number().int().describe('Absolute count of unique users who matched step 1'),
  usersAtEnd: z.number().int().describe('Absolute count of unique users who matched the last step'),
  steps: z.array(funnelStepResultSchema).describe('One result entry per input step, in order'),
}).openapi('FunnelQueryResponse');

export type FunnelQueryResponse = z.infer<typeof funnelQueryResponseSchema>;

/**
 * Schema for creating a new saved funnel query.
 */
export const createSavedFunnelQuerySchema = z.object({
  name: z.string().min(1).max(255).describe('Unique name for this saved funnel query within the project'),
  query: funnelQuerySchema.describe('The full funnel query configuration to save'),
  isShared: z.boolean().default(false).describe('Whether this query is visible to all operators in the project'),
});

/**
 * Schema for updating a saved funnel query.
 * All content fields are optional; version is required for optimistic locking.
 */
export const updateSavedFunnelQuerySchema = z.object({
  name: z.string().min(1).max(255).optional().describe('Updated name for this saved funnel query'),
  query: funnelQuerySchema.optional().describe('Updated funnel query configuration'),
  isShared: z.boolean().optional().describe('Updated sharing flag'),
  version: z.number().int().min(1).describe('Current version number for optimistic locking'),
});

/**
 * Schema for the request body of a delete saved funnel query operation.
 */
export const deleteSavedFunnelQueryBodySchema = z.object({
  version: z.number().int().min(1).describe('Current version number for optimistic locking'),
});

/**
 * Shape returned by all saved funnel query endpoints.
 * Intentionally omits a metadata field — funnel charts have a fixed representation.
 */
export const savedFunnelQueryResponseSchema = z.object({
  id: z.string().describe('Unique identifier of the saved funnel query'),
  name: z.string().describe('Name of the saved funnel query'),
  projectId: z.string().describe('Project this query belongs to'),
  operatorId: z.string().nullable().describe('Operator who created this query, or null if the operator has been deleted'),
  query: funnelQuerySchema.describe('The saved funnel query configuration'),
  isShared: z.boolean().describe('Whether this query is visible to all operators in the project'),
  version: z.number().int().describe('Version number for optimistic locking'),
  createdAt: z.coerce.date().nullable().describe('Timestamp when the query was created'),
  updatedAt: z.coerce.date().nullable().describe('Timestamp when the query was last updated'),
}).openapi('SavedFunnelQuery');

/**
 * Route params schema for endpoints that include both projectId and saved query id.
 */
export const savedFunnelQueryRouteParamsSchema = z.object({
  projectId: z.string().describe('Project identifier'),
  id: z.string().describe('Saved funnel query identifier'),
});

export type CreateSavedFunnelQueryRequest = z.infer<typeof createSavedFunnelQuerySchema>;
export type UpdateSavedFunnelQueryRequest = z.infer<typeof updateSavedFunnelQuerySchema>;
export type DeleteSavedFunnelQueryRequest = z.infer<typeof deleteSavedFunnelQueryBodySchema>;
export type SavedFunnelQueryResponse = z.infer<typeof savedFunnelQueryResponseSchema>;
