import EmailReplyParser from 'email-reply-parser';
import { logger } from '../../../utils/logger';

/**
 * Extended quote header patterns for locales not covered by email-reply-parser defaults.
 *
 * The library already covers: EN, FR, ES, IT, PT, DE, NL, PL, DA, FI, RU, ZH, KO, JA
 * plus generic "From:", "Von:", "De:", "Van:", "Da:" sender patterns.
 *
 * These additional patterns cover:
 *   - Eastern European: HU, CS, SK, RO, HR/RS, BG, EL, UK, LT, LV, ET, SL
 *   - Scandinavian: NO, SV, IS
 *   - Asian: VI, ID, MS, TH, HI, BN, TA, ZH (extra)
 *
 * All patterns are anchored to year prefixes (20xx/25xx) to avoid matching user content.
 * Generic "NAME wrote:" patterns are omitted — the library handles those safely.
 * 
 * This is generated by LLM and needs to be verified/fixed if necessary.
 */
const EXTENDED_QUOTE_HEADERS: RegExp[] = [
  // Hungarian: 2024. január 1., 12:00 írta NAME:
  /^20[0-9]{2}\..+\sírta\s.+:$/,
  // Czech: 1. 1. 2024 v 12:00 napsal(a) NAME:
  /^20[0-9]{2}.*napsal\(a\)\s.+:$/,
  // Slovak: 1. 1. 2024 o 12:00 napísal(a) NAME:
  /^20[0-9]{2}.*napísal\(a\)\s.+:$/,
  // Romanian: 1 ian 2024 la 12:00 a scris NAME:
  /^20[0-9]{2}.*a scris\s.+:$/,
  // Croatian/Serbian: 1. sije 2024. u 12:00 je napisao NAME:
  /^20[0-9]{2}.*je napisao\s.+:$/,
  // Bulgarian: 1 яну 2024 г., 12:00 написа NAME:
  /^20[0-9]{2}.*написа\s.+:$/,
  // Greek: 1 Ιαν 2024 12:00 έγραψε NAME:
  /^20[0-9]{2}.*έγραψε\s.+:$/,
  // Ukrainian: 1 січ. 2024 о 12:00 написав NAME:
  /^20[0-9]{2}.*написав\s.+:$/,
  // Lithuanian: 2024-01-01 12:00 parašė NAME:
  /^20[0-9]{2}.*parašė\s.+:$/,
  // Latvian: 2024. gada 1. janv. plkst. 12:00 rakstīja NAME:
  /^20[0-9]{2}.*rakstīja\s.+:$/,
  // Estonian: 1. jaan. 2024 kell 12:00 kirjutas NAME:
  /^20[0-9]{2}.*kirjutas\s.+:$/,
  // Slovenian: 1. jan 2024 ob 12:00 je napisal NAME:
  /^20[0-9]{2}.*je napisal\s.+:$/,
  // Norwegian: 1. jan. 2024 kl. 12:00 skrev NAME:
  /^20[0-9]{2}.*skrev\s.+:$/,
  // Icelandic: 1. jan. 2024 kl. 12:00 skrifaði NAME:
  /^20[0-9]{2}.*skrifaði\s.+:$/,
  // Vietnamese: Vào lúc 1/1/2024 12:00, NAME đã viết:
  /^Vào lúc\s.+\sđã viết:$/,
  // Indonesian: Pada 1 Jan 2024 12:00, NAME menulis:
  /^Pada\s.+\smenulis:$/,
  // Malay: Pada 1 Jan 2024 12:00, NAME menulis:
  /^Pada\s.+\smenulis:$/,
  // Thai: 1 ม.ค. 2567 12:00 NAME wrote:
  /^25[0-9]{2}.*wrote:$/,
  // Hindi: 1 जनवरी 2024 को 12:00 बजे NAME ने लिखा:
  /^20[0-9]{2}.*ने लिखा:$/,
  // Bengali: 1 জানুয়ারি 2024, 12:00 NAME লিখেছেন:
  /^20[0-9]{2}.*লিখেছেন:$/,
  // Tagalog: Enero 1, 2024 12:00 PM sinabi ni NAME:
  /^20[0-9]{2}.*sinabi ni\s.+$/,
  // Chinese extra: 发件人: NAME <EMAIL>
  /^发件人:.+<.+>$/,
  // Japanese extra: 送信者: NAME <EMAIL>
  /^送信者:.+<.+>$/,
  // Korean extra: 보낸 사람: NAME <EMAIL>
  /^보낸 사람:.+$/,
];

/**
 * Extended signature patterns for additional locales.
 */
const EXTENDED_SIGNATURES: RegExp[] = [
  // Eastern European
  /^Pozdrawiam,?$/mi,
  /^Z poważaniem,?$/mi,
  /^Lepšie pozdravy,?$/mi,
  /^S pozdravom,?$/mi,
  /^Üdvözlettel,?$/mi,
  /^Tisztelettel,?$/mi,
  /^Cu stimă,?$/mi,
  /^Cele mai bune,?$/mi,
  // Scandinavian
  /^Med venlig hilsen,?$/mi,
  /^Vänliga hälsningar,?$/mi,
  // Baltic
  /^Labai,?$/mi,
  /^Ar cieņu,?$/mi,
  // Thai
  /^ขอแสดงความนับถือ,?$/,
  // Vietnamese
  /^Trân trọng,?$/,
  // Indonesian
  /^Salam,?$/mi,
  /^Hormat kami,?$/mi,
];

/**
 * Strip lines matching extended quote header and signature patterns from text.
 * Runs as a pre-processing step before the library's parser.
 */
function stripExtendedPatterns(text: string): string {
  const lines = text.split('\n');
  const filtered = lines.filter((line) => {
    const trimmed = line.trim();
    if (
      EXTENDED_QUOTE_HEADERS.some((regex) => regex.test(trimmed)) ||
      EXTENDED_SIGNATURES.some((regex) => regex.test(trimmed))
    ) {
      return false;
    }
    return true;
  });
  return filtered.join('\n');
}

/**
 * Strip quoted reply history and signatures from an email body.
 * Returns only the visible (new) text from the email.
 *
 * Uses a two-pass approach:
 * 1. Pre-process: strip extended locale patterns not in the library
 * 2. Library: run email-reply-parser for standard patterns + `>` quoted text
 */
export function stripEmailQuotes(text: string): string {
  if (!text) return '';

  try {
    const preProcessed = stripExtendedPatterns(text);
    return new EmailReplyParser().read(preProcessed).getVisibleText().trim();
  } catch (error) {
    logger.warn({ error }, 'EmailBodyCleaner: failed to strip email quotes, returning original text');
    return text.trim();
  }
}
